/*
 * © 2026 Nokia
 * Licensed under the BSD 3-Clause Clear License
 * SPDX-License-Identifier: BSD-3-Clause-Clear
 */

/*
 * RATLS Python Bridge - C Extension
 *
 * Bridges Python to RATLS's patched OpenSSL for per-connection attestation.
 * Exposes SSL_CTX_add_custom_ext() and SSL_export_handshake_binder_secret()
 * to Python, allowing TLS extension handlers to be registered.
 *
 * SEV-SNP variant: per-handshake attestation report is generated by invoking
 * `snpguest` (which talks to /dev/sev-guest in the CVM kernel).  REPORT_DATA
 * is bound to SHA256(binder_secret) so the report cryptographically commits
 * to this specific TLS handshake transcript.  The binder-secret API is the
 * TEE-agnostic part of RATLS; only the quote source changed from Gramine's
 * /dev/attestation/* to snpguest.
 */

#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <openssl/tls1.h>
#include <openssl/sha.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

/* TLS extension numbers for RATLS */
#define EXT_RA_REQ 420  /* Client requests attestation from server */
#define EXT_RA_RES 421  /* Server/Client responds with quote */

/* Global Python callback functions */
static PyObject *py_generate_quote_callback = NULL;   /* Server: generate quote */
static PyObject *py_verify_quote_callback = NULL;     /* Client: verify quote */

/* Python's internal SSLContext structure (from Modules/_ssl.c) */
typedef struct {
    PyObject_HEAD
    SSL_CTX *ctx;
    /* ... other fields we don't need */
} PySSLContext;

/*
 * Extract binder_secret from OpenSSL SSL object using patched API.
 * Returns 48-byte binder secret = SHA256(handshake_secret || handshake_traffic_hash)
 */
static int extract_binder_secret(SSL *ssl, unsigned char *out, size_t outlen) {
    /* Declare the patched OpenSSL function */
    extern int SSL_export_handshake_binder_secret(SSL *s, unsigned char *out, size_t olen);

    if (outlen < 48) {
        return 0;
    }

    return SSL_export_handshake_binder_secret(ssl, out, 48);
}

/*
 * Read a regular file fully into a malloc'd buffer.  Caller frees *out.
 */
static int slurp_file(const char *path, unsigned char **out, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) return -1;
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return -1; }
    long sz = ftell(f);
    if (sz <= 0 || sz > 65536) { fclose(f); return -1; }
    rewind(f);
    unsigned char *buf = malloc((size_t)sz);
    if (!buf) { fclose(f); return -1; }
    if (fread(buf, 1, (size_t)sz, f) != (size_t)sz) {
        free(buf); fclose(f); return -1;
    }
    fclose(f);
    *out = buf;
    *out_len = (size_t)sz;
    return 0;
}

/*
 * Generate an SEV-SNP attestation evidence bundle bound to the TLS
 * binder_secret.  The bundle is what cTLS / HTTPA/2 / RATLS now send on
 * the wire; the verifier (client) submits SnpReport+VcekCertChain to Azure
 * MAA's /attest/SevSnpVm and locally cross-checks the TPM2 quote.
 *
 * Implementation: spawns common/snp_bundle_cli.py which calls
 * common.snp_attestation.build_snp_evidence_bundle(nonce=binder_secret).
 * Each handshake gets its own tmpdir (mkdtemp) so concurrent handshakes
 * don't race on shared paths.
 *
 * The CLI path can be overridden by RATLS_BUNDLE_CLI environment variable;
 * default is `<APP_HOME>/Janus/janus/common/snp_bundle_cli.py`.
 *
 * Returns bundle length on success, -1 on error.  Caller frees *out_quote.
 */
static int generate_snp_quote_c(const unsigned char *binder_secret,
                                unsigned char **out_quote) {
    char tmpdir[] = "/tmp/ratls_snp_XXXXXX";
    if (!mkdtemp(tmpdir)) {
        fprintf(stderr, "RATLS Bridge: mkdtemp failed: %s\n", strerror(errno));
        return -1;
    }

    char nonce_hex[97];  /* 48 bytes binder_secret -> 96 hex + nul */
    for (int i = 0; i < 48; i++) {
        snprintf(nonce_hex + 2*i, 3, "%02x", binder_secret[i]);
    }

    char bundle_path[256], cmd[2048];
    snprintf(bundle_path, sizeof(bundle_path), "%s/bundle.bin", tmpdir);

    static char cli_buf[512];
    const char *cli = getenv("RATLS_BUNDLE_CLI");
    if (!cli || !*cli) {
        /* default: the artifact checkout under APP_HOME (deploy/backend_setup.sh sets RATLS_BUNDLE_CLI explicitly) */
        const char *home = getenv("APP_HOME");
        if (!home || !*home) home = "/home/janus";
        snprintf(cli_buf, sizeof(cli_buf), "%s/Janus/janus/common/snp_bundle_cli.py", home);
        cli = cli_buf;
    }

    /* Pipe the hex nonce on stdin; the CLI writes the bundle to bundle_path. */
    snprintf(cmd, sizeof(cmd),
             "echo -n '%s' | python3 '%s' '%s' > /dev/null 2>&1",
             nonce_hex, cli, bundle_path);

    int rc = -1;
    if (system(cmd) != 0) {
        fprintf(stderr, "RATLS Bridge: snp_bundle_cli failed (cmd: %s)\n", cmd);
        goto cleanup;
    }

    unsigned char *buf = NULL;
    size_t sz = 0;
    if (slurp_file(bundle_path, &buf, &sz) != 0) {
        fprintf(stderr, "RATLS Bridge: cannot read %s\n", bundle_path);
        goto cleanup;
    }

    *out_quote = buf;
    rc = (int)sz;

cleanup:
    unlink(bundle_path);
    rmdir(tmpdir);
    return rc;
}

/*
 * TLS Extension Callback: Add RA Request (extension 420) on client
 * 
 * Called by OpenSSL when client wants to request attestation from server.
 */
static int add_ra_request_cb(SSL *ssl, unsigned int ext_type,
                             unsigned int context,
                             const unsigned char **out, size_t *outlen,
                             X509 *x, size_t chainidx,
                             int *al, void *add_arg) {
    /* Send empty extension to signal we want attestation */
    *out = NULL;
    *outlen = 0;
    return 1;
}

/*
 * TLS Extension Callback: Parse RA Request (extension 420) on server
 * 
 * Called by OpenSSL when server receives RA request from client.
 */
static int parse_ra_request_cb(SSL *ssl, unsigned int ext_type,
                               unsigned int context,
                               const unsigned char *in, size_t inlen,
                               X509 *x, size_t chainidx,
                               int *al, void *parse_arg) {
    /* Server received RA request from client - just acknowledge it */
    return 1;
}

/*
 * TLS Extension Callback: Add RA Response (extension 421)
 * 
 * Called by OpenSSL during TLS handshake when server needs to send attestation.
 * Extracts binder_secret, calls Python callback to generate SGX quote, sends quote.
 */
static int add_ra_response_cb(SSL *ssl, unsigned int ext_type,
                              unsigned int context,
                              const unsigned char **out, size_t *outlen,
                              X509 *x, size_t chainidx,
                              int *al, void *add_arg) {
    /* Only generate quote for root certificate (chainidx == 0) in Certificate message */
    if (context != 0x1000 || chainidx != 0) {  /* 0x1000 = SSL_EXT_TLS1_3_CERTIFICATE */
        return 0;  /* Don't add extension for this context */
    }

    /* Extract binder secret from TLS handshake */
    unsigned char binder_secret[48];
    if (extract_binder_secret(ssl, binder_secret, 48) != 1) {
        fprintf(stderr, "RATLS Bridge: Failed to extract binder_secret\n");
        return 0;
    }

    /* Generate SEV-SNP attestation bundle by calling the Python callback
     * registered by setup_ratls_server.  The callback receives the 48-byte
     * binder_secret and returns the bundle bytes (built in-process by
     * common.snp_attestation.build_snp_evidence_bundle).  This keeps the
     * server-gen path equivalent to HTTPA/2's: no subprocess, no Python
     * interpreter startup per handshake — same Python process, same helper.
     *
     * If no Python callback is registered (e.g. during boot or in a unit
     * test), we fall back to the C-side subprocess implementation.
     */
    unsigned char *quote_buf = NULL;
    int quote_len = -1;

    if (py_generate_quote_callback) {
        PyGILState_STATE gstate = PyGILState_Ensure();
        PyObject *py_secret = PyBytes_FromStringAndSize((char*)binder_secret, 48);
        if (!py_secret) {
            PyGILState_Release(gstate);
            return 0;
        }
        PyObject *py_result = PyObject_CallFunctionObjArgs(
            py_generate_quote_callback, py_secret, NULL);
        Py_DECREF(py_secret);
        if (!py_result) {
            PyErr_Print();
            PyGILState_Release(gstate);
            return 0;
        }
        if (PyBytes_Check(py_result)) {
            Py_ssize_t len = PyBytes_GET_SIZE(py_result);
            quote_buf = (unsigned char *)malloc((size_t)len);
            if (quote_buf) {
                memcpy(quote_buf, PyBytes_AS_STRING(py_result), (size_t)len);
                quote_len = (int)len;
            }
        }
        Py_DECREF(py_result);
        PyGILState_Release(gstate);
    } else {
        quote_len = generate_snp_quote_c(binder_secret, &quote_buf);
    }

    if (quote_len < 0 || !quote_buf) {
        fprintf(stderr, "RATLS Bridge: Failed to generate SEV-SNP report\n");
        return 0;
    }

    /* Allocate memory for extension data (OpenSSL will free it) */
    unsigned char *ext_data = OPENSSL_malloc(quote_len);
    if (!ext_data) {
        free(quote_buf);
        return 0;
    }

    memcpy(ext_data, quote_buf, quote_len);
    free(quote_buf);

    *out = ext_data;
    *outlen = quote_len;
    return 1;
}

/*
 * TLS Extension Callback: Free RA Response 
 */
static void free_ra_response_cb(SSL *s, unsigned int ext_type,
                                unsigned int context,
                                const unsigned char *out,
                                void *add_arg) {
    if (out) {
        OPENSSL_free((void*)out);
    }
}

/*
 * TLS Extension Callback: Parse RA Response (extension 421)
 * 
 * Called by OpenSSL when client receives quote from server.
 * Extracts binder_secret, calls Python callback to verify quote via Azure MAA.
 */
static int parse_ra_response_cb(SSL *ssl, unsigned int ext_type,
                                unsigned int context,
                                const unsigned char *in, size_t inlen,
                                X509 *x, size_t chainidx,
                                int *al, void *parse_arg) {
    /* Extract binder secret from TLS handshake */
    unsigned char binder_secret[48];
    if (extract_binder_secret(ssl, binder_secret, 48) != 1) {
        fprintf(stderr, "RATLS Bridge: Failed to extract binder_secret\n");
        return 0;
    }
    
    /* Call Python callback to verify quote */
    PyGILState_STATE gstate = PyGILState_Ensure();
    
    PyObject *py_quote = PyBytes_FromStringAndSize((char*)in, inlen);
    PyObject *py_secret = PyBytes_FromStringAndSize((char*)binder_secret, 48);
    
    if (!py_quote || !py_secret) {
        Py_XDECREF(py_quote);
        Py_XDECREF(py_secret);
        PyGILState_Release(gstate);
        return 0;
    }
    
    /* Call Python callback with (binder_secret, quote) order */
    PyObject *py_result = PyObject_CallFunctionObjArgs(
        py_verify_quote_callback, py_secret, py_quote, NULL
    );
    
    Py_DECREF(py_quote);
    Py_DECREF(py_secret);
    
    if (!py_result) {
        PyErr_Print();
        PyGILState_Release(gstate);
        return 0;
    }
    
    int verification_ok = PyObject_IsTrue(py_result);
    Py_DECREF(py_result);
    PyGILState_Release(gstate);
    
    return verification_ok ? 1 : 0;
}

/*
 * Python-exposed function: setup_ratls_server
 * 
 * Registers TLS extension handlers for RATLS server mode.
 * Server generates quotes and sends them via extension 421.
 */
static PyObject* setup_ratls_server(PyObject *self, PyObject *args) {
    PyObject *py_ssl_context;
    PyObject *py_generate_cb;
    
    if (!PyArg_ParseTuple(args, "OO", &py_ssl_context, &py_generate_cb)) {
        return NULL;
    }
    
    /* Store Python callback */
    Py_XDECREF(py_generate_quote_callback);
    py_generate_quote_callback = py_generate_cb;
    Py_INCREF(py_generate_quote_callback);
    
    /* Extract SSL_CTX* by directly casting PySSLContext */
    PySSLContext *ssl_ctx_obj = (PySSLContext *)py_ssl_context;
    SSL_CTX *ctx = ssl_ctx_obj->ctx;
    
    if (!ctx) {
        PyErr_SetString(PyExc_TypeError, "Invalid SSL_CTX pointer");
        return NULL;
    }
    
    /* Register TLS extension 420 (RA Request) - server parses client's request from ClientHello */
    if (SSL_CTX_add_custom_ext(ctx, EXT_RA_REQ,
                               SSL_EXT_CLIENT_HELLO | SSL_EXT_TLS1_3_SERVER_HELLO,
                               NULL, NULL, NULL,  /* Server doesn't send 420, only receives */
                               parse_ra_request_cb, NULL) != 1) {
        PyErr_SetString(PyExc_RuntimeError, "Failed to register TLS extension 420 (server-side)");
        return NULL;
    }

    /* Register TLS extension 421 (RA Response) - server sends quote in Certificate message */
    if (SSL_CTX_add_custom_ext(ctx, EXT_RA_RES,
                               SSL_EXT_TLS1_3_CERTIFICATE | SSL_EXT_CLIENT_HELLO | SSL_EXT_TLS1_3_CERTIFICATE_REQUEST,
                               add_ra_response_cb, free_ra_response_cb, NULL,
                               NULL, NULL) != 1) {
        PyErr_SetString(PyExc_RuntimeError, "Failed to register TLS extension 421");
        return NULL;
    }

    Py_RETURN_NONE;
}

/*
 * Python-exposed function: setup_ratls_client
 * 
 * Registers TLS extension handlers for RATLS client mode.
 * Client requests attestation (extension 420) and verifies quote (extension 421).
 */
static PyObject* setup_ratls_client(PyObject *self, PyObject *args) {
    PyObject *py_ssl_context;
    PyObject *py_verify_cb;
    
    if (!PyArg_ParseTuple(args, "OO", &py_ssl_context, &py_verify_cb)) {
        return NULL;
    }
    
    /* Store Python callback */
    Py_XDECREF(py_verify_quote_callback);
    py_verify_quote_callback = py_verify_cb;
    Py_INCREF(py_verify_quote_callback);
    
    /* Extract SSL_CTX* by directly casting PySSLContext */
    PySSLContext *ssl_ctx_obj = (PySSLContext *)py_ssl_context;
    SSL_CTX *ctx = ssl_ctx_obj->ctx;
    
    if (!ctx) {
        PyErr_SetString(PyExc_TypeError, "Invalid SSL_CTX pointer");
        return NULL;
    }
    
    /* Register TLS extension 420 (RA Request) - client requests attestation */
    if (SSL_CTX_add_custom_ext(ctx, EXT_RA_REQ,
                               SSL_EXT_CLIENT_HELLO,
                               add_ra_request_cb, NULL, NULL,  /* Send empty request */
                               NULL, NULL) != 1) {
        PyErr_SetString(PyExc_RuntimeError, "Failed to register RA request extension");
        return NULL;
    }

    /* Register TLS extension 421 (RA Response) - client parses server's quote from Certificate */
    if (SSL_CTX_add_custom_ext(ctx, EXT_RA_RES,
                               SSL_EXT_TLS1_3_CERTIFICATE | SSL_EXT_CLIENT_HELLO,
                               add_ra_request_cb, NULL, NULL,  /* Send empty in ClientHello */
                               parse_ra_response_cb, NULL) != 1) {
        PyErr_SetString(PyExc_RuntimeError, "Failed to register RA response extension");
        return NULL;
    }

    Py_RETURN_NONE;
}

/*
 * Module method definitions
 */
static PyMethodDef RatlsMethods[] = {
    {"setup_ratls_server", setup_ratls_server, METH_VARARGS,
     "Configure SSL context for RATLS server with attestation generation."},
    {"setup_ratls_client", setup_ratls_client, METH_VARARGS,
     "Configure SSL context for RATLS client with attestation verification."},
    {NULL, NULL, 0, NULL}
};

/*
 * Module definition
 */
static struct PyModuleDef ratlsmodule = {
    PyModuleDef_HEAD_INIT,
    "ratls_bridge",
    "Python bridge to RATLS OpenSSL extensions for per-connection attestation",
    -1,
    RatlsMethods
};

/*
 * Module initialization
 */
PyMODINIT_FUNC PyInit_ratls_bridge(void) {
    return PyModule_Create(&ratlsmodule);
}
