#!/bin/bash
# © 2026 Nokia
# Licensed under the BSD 3-Clause Clear License
# SPDX-License-Identifier: BSD-3-Clause-Clear

#
# Generate Pebble's HTTPS-listener certificate, signed by the Janus CA chain
# (ca_certs/intermediate-ca.pem), so the frontend's ACME client — which trusts
# the Janus root — trusts Pebble's ACME endpoint.
#
# This is a Janus helper (not part of upstream Pebble). fetch_pebble.sh copies
# it into the cloned Pebble's test/certs/ so the frontend image build can run it.
# It expects the Janus CA chain to already exist at ../../ca_certs/ (generated by
# ca_certs/generate_ca_certificates.sh).
#

set -e

CERTS_DIR="$(cd "$(dirname "$0")" && pwd)"
CA_DIR="$CERTS_DIR/../../ca_certs"

cd "$CERTS_DIR"

echo "Generating Pebble HTTPS listener certificate..."

# Generate private key for localhost
openssl genrsa -out localhost-key.pem 2048

# Create CSR
openssl req -new -key localhost-key.pem -out localhost.csr \
    -subj "/C=US/ST=Test/L=Test/O=Pebble/CN=localhost"

# Create extension file for SAN
cat > localhost-ext.cnf <<EOF
basicConstraints = CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = localhost
DNS.2 = pebble
IP.1 = 127.0.0.1
EOF

# Sign with intermediate CA
openssl x509 -req -days 365 -in localhost.csr \
    -CA "$CA_DIR/intermediate-ca.pem" \
    -CAkey "$CA_DIR/intermediate-ca-key.pem" \
    -CAcreateserial \
    -out localhost.pem \
    -extfile localhost-ext.cnf

# Create a minica.pem symlink for compatibility with existing scripts
ln -sf "$CA_DIR/root-ca.pem" pebble.minica.pem

# Cleanup
rm -f localhost.csr localhost-ext.cnf

echo "✓ Pebble HTTPS certificate created"
openssl x509 -in localhost.pem -noout -subject -dates

echo "✅ Pebble test certificates ready!"
